# 本 Dockerfile 用于构建在 CI 环境中执行单元测试的项目镜像。说明：
#
# - 目标镜像并不包含 bkms-server 的可执行文件，仅下载了相关依赖，可用于执行单测；
# - 必须在 bkms-govern 根目录下执行 docker build 命令（因为依赖 libs/bkms-adapter）；
#
# 示例:
#    docker build -f bkms-server/Dockerfile.ci_ut \
#       -t bkms/bkms-server-ci-ut:0.0.1-alpha.1 \
#       --build-arg GOPROXY="https://goproxy.cn,direct" \
#       --build-arg GOSUMDB="<...>" .
#
FROM golang:1.25.7-alpine3.22 AS builder

ENV TZ=Asia/Shanghai

RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.tencent.com/g' /etc/apk/repositories

RUN apk --update --no-cache add make git curl tzdata

ARG GOPROXY
ARG GOSUMDB

WORKDIR /go/src/

# Copy local adapter module.
COPY libs/bkms-adapter /go/libs/bkms-adapter

# Prepare for go mod download
COPY bkms-server/go.mod go.mod
COPY bkms-server/go.sum go.sum

# Download go module dependencies
RUN go mod download

COPY bkms-server/ .
# Install essential tools for unit testing
RUN make ginkgo
