// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package usertoken

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockTokenClient creates a new instance of MockTokenClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTokenClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTokenClient {
	mock := &MockTokenClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTokenClient is an autogenerated mock type for the TokenClient type
type MockTokenClient struct {
	mock.Mock
}

type MockTokenClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTokenClient) EXPECT() *MockTokenClient_Expecter {
	return &MockTokenClient_Expecter{mock: &_m.Mock}
}

// GetToken provides a mock function for the type MockTokenClient
func (_mock *MockTokenClient) GetToken(ctx context.Context, username string, credentials map[string]string, envName string, needNewToken bool) (*AccessToken, error) {
	ret := _mock.Called(ctx, username, credentials, envName, needNewToken)

	if len(ret) == 0 {
		panic("no return value specified for GetToken")
	}

	var r0 *AccessToken
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, map[string]string, string, bool) (*AccessToken, error)); ok {
		return returnFunc(ctx, username, credentials, envName, needNewToken)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, map[string]string, string, bool) *AccessToken); ok {
		r0 = returnFunc(ctx, username, credentials, envName, needNewToken)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*AccessToken)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, map[string]string, string, bool) error); ok {
		r1 = returnFunc(ctx, username, credentials, envName, needNewToken)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTokenClient_GetToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetToken'
type MockTokenClient_GetToken_Call struct {
	*mock.Call
}

// GetToken is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
//   - credentials map[string]string
//   - envName string
//   - needNewToken bool
func (_e *MockTokenClient_Expecter) GetToken(ctx interface{}, username interface{}, credentials interface{}, envName interface{}, needNewToken interface{}) *MockTokenClient_GetToken_Call {
	return &MockTokenClient_GetToken_Call{Call: _e.mock.On("GetToken", ctx, username, credentials, envName, needNewToken)}
}

func (_c *MockTokenClient_GetToken_Call) Run(run func(ctx context.Context, username string, credentials map[string]string, envName string, needNewToken bool)) *MockTokenClient_GetToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 map[string]string
		if args[2] != nil {
			arg2 = args[2].(map[string]string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 bool
		if args[4] != nil {
			arg4 = args[4].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockTokenClient_GetToken_Call) Return(accessToken *AccessToken, err error) *MockTokenClient_GetToken_Call {
	_c.Call.Return(accessToken, err)
	return _c
}

func (_c *MockTokenClient_GetToken_Call) RunAndReturn(run func(ctx context.Context, username string, credentials map[string]string, envName string, needNewToken bool) (*AccessToken, error)) *MockTokenClient_GetToken_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserInfo provides a mock function for the type MockTokenClient
func (_mock *MockTokenClient) GetUserInfo(ctx context.Context, token string) (string, error) {
	ret := _mock.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for GetUserInfo")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return returnFunc(ctx, token)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, token)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, token)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTokenClient_GetUserInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserInfo'
type MockTokenClient_GetUserInfo_Call struct {
	*mock.Call
}

// GetUserInfo is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *MockTokenClient_Expecter) GetUserInfo(ctx interface{}, token interface{}) *MockTokenClient_GetUserInfo_Call {
	return &MockTokenClient_GetUserInfo_Call{Call: _e.mock.On("GetUserInfo", ctx, token)}
}

func (_c *MockTokenClient_GetUserInfo_Call) Run(run func(ctx context.Context, token string)) *MockTokenClient_GetUserInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTokenClient_GetUserInfo_Call) Return(s string, err error) *MockTokenClient_GetUserInfo_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockTokenClient_GetUserInfo_Call) RunAndReturn(run func(ctx context.Context, token string) (string, error)) *MockTokenClient_GetUserInfo_Call {
	_c.Call.Return(run)
	return _c
}

// RefreshToken provides a mock function for the type MockTokenClient
func (_mock *MockTokenClient) RefreshToken(ctx context.Context, refreshToken string, envName string, needNewToken bool) (*AccessToken, error) {
	ret := _mock.Called(ctx, refreshToken, envName, needNewToken)

	if len(ret) == 0 {
		panic("no return value specified for RefreshToken")
	}

	var r0 *AccessToken
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, bool) (*AccessToken, error)); ok {
		return returnFunc(ctx, refreshToken, envName, needNewToken)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, bool) *AccessToken); ok {
		r0 = returnFunc(ctx, refreshToken, envName, needNewToken)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*AccessToken)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, bool) error); ok {
		r1 = returnFunc(ctx, refreshToken, envName, needNewToken)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTokenClient_RefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RefreshToken'
type MockTokenClient_RefreshToken_Call struct {
	*mock.Call
}

// RefreshToken is a helper method to define mock.On call
//   - ctx context.Context
//   - refreshToken string
//   - envName string
//   - needNewToken bool
func (_e *MockTokenClient_Expecter) RefreshToken(ctx interface{}, refreshToken interface{}, envName interface{}, needNewToken interface{}) *MockTokenClient_RefreshToken_Call {
	return &MockTokenClient_RefreshToken_Call{Call: _e.mock.On("RefreshToken", ctx, refreshToken, envName, needNewToken)}
}

func (_c *MockTokenClient_RefreshToken_Call) Run(run func(ctx context.Context, refreshToken string, envName string, needNewToken bool)) *MockTokenClient_RefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 bool
		if args[3] != nil {
			arg3 = args[3].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockTokenClient_RefreshToken_Call) Return(accessToken *AccessToken, err error) *MockTokenClient_RefreshToken_Call {
	_c.Call.Return(accessToken, err)
	return _c
}

func (_c *MockTokenClient_RefreshToken_Call) RunAndReturn(run func(ctx context.Context, refreshToken string, envName string, needNewToken bool) (*AccessToken, error)) *MockTokenClient_RefreshToken_Call {
	_c.Call.Return(run)
	return _c
}
