// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package env_test

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockFeatureEnvNamespaceInitializer creates a new instance of MockFeatureEnvNamespaceInitializer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFeatureEnvNamespaceInitializer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFeatureEnvNamespaceInitializer {
	mock := &MockFeatureEnvNamespaceInitializer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockFeatureEnvNamespaceInitializer is an autogenerated mock type for the FeatureEnvNamespaceInitializer type
type MockFeatureEnvNamespaceInitializer struct {
	mock.Mock
}

type MockFeatureEnvNamespaceInitializer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFeatureEnvNamespaceInitializer) EXPECT() *MockFeatureEnvNamespaceInitializer_Expecter {
	return &MockFeatureEnvNamespaceInitializer_Expecter{mock: &_m.Mock}
}

// Initialize provides a mock function for the type MockFeatureEnvNamespaceInitializer
func (_mock *MockFeatureEnvNamespaceInitializer) Initialize(ctx context.Context, clusterID string, namespace string, ownerLabels map[string]string) error {
	ret := _mock.Called(ctx, clusterID, namespace, ownerLabels)

	if len(ret) == 0 {
		panic("no return value specified for Initialize")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, map[string]string) error); ok {
		r0 = returnFunc(ctx, clusterID, namespace, ownerLabels)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockFeatureEnvNamespaceInitializer_Initialize_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Initialize'
type MockFeatureEnvNamespaceInitializer_Initialize_Call struct {
	*mock.Call
}

// Initialize is a helper method to define mock.On call
//   - ctx context.Context
//   - clusterID string
//   - namespace string
//   - ownerLabels map[string]string
func (_e *MockFeatureEnvNamespaceInitializer_Expecter) Initialize(ctx interface{}, clusterID interface{}, namespace interface{}, ownerLabels interface{}) *MockFeatureEnvNamespaceInitializer_Initialize_Call {
	return &MockFeatureEnvNamespaceInitializer_Initialize_Call{Call: _e.mock.On("Initialize", ctx, clusterID, namespace, ownerLabels)}
}

func (_c *MockFeatureEnvNamespaceInitializer_Initialize_Call) Run(run func(ctx context.Context, clusterID string, namespace string, ownerLabels map[string]string)) *MockFeatureEnvNamespaceInitializer_Initialize_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 map[string]string
		if args[3] != nil {
			arg3 = args[3].(map[string]string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockFeatureEnvNamespaceInitializer_Initialize_Call) Return(err error) *MockFeatureEnvNamespaceInitializer_Initialize_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockFeatureEnvNamespaceInitializer_Initialize_Call) RunAndReturn(run func(ctx context.Context, clusterID string, namespace string, ownerLabels map[string]string) error) *MockFeatureEnvNamespaceInitializer_Initialize_Call {
	_c.Call.Return(run)
	return _c
}
