{{- if .Values.utility.rbac.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "bkms-server.serviceAccountName" . }}
  labels:
    {{- include "bkms-server.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "bkms-server.fullname" . }}-role
  labels:
    {{- include "bkms-server.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - batch
    resources:
      - jobs
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "bkms-server.fullname" . }}-role-binding
  labels:
    {{- include "bkms-server.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "bkms-server.fullname" . }}-role
subjects:
  - kind: ServiceAccount
    name: {{ include "bkms-server.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
